var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import Colors from './../../styles/Colors';
import Breakpoints from '../../styles/Breakpoints';
var getErrorStyle = function () { return "\n  color: " + Colors.red100 + ";\n"; };
export var Container = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: inline;\n  \n  ", "\n  \n  ", "\n"], ["\n  display: inline;\n  \n  ", "\n  \n  ",
    "\n"])), function (props) { return props.hasError ? getErrorStyle() : ""; }, Breakpoints.global("\n    display: block;\n    margin: 0 auto 15px; \n    text-align: center;\n  "));
export var LabelText = styled.p(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: inline-block;\n  margin: 0;\n"], ["\n  display: inline-block;\n  margin: 0;\n"])));
export var Label = styled.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  cursor: pointer;\n  font-weight: 500;\n  position: relative;\n  user-select: none;\n  transition: color 300ms;\n\n  &:before,\n  &:after {\n    display: inline-block;\n  }\n\n  &:before {\n    background: ", ";\n    border: 1px solid ", ";\n    border-radius: 0;\n    content: \"\";\n    height: 13px;\n    margin: -2px 5px 0 0;\n    transition: background 300ms;\n    vertical-align: middle;\n    width: 13px;\n  }\n\n  &:after {\n    border: solid ", ";\n    border-width: 0 2px 2px 0;\n    content: \"\";\n    height: 7px;\n    left: 5px;\n    position: absolute;\n    opacity: 0;\n    top: 4px;\n    transform: rotate(45deg);\n    transition: border-color 300ms, opacity 300ms;\n    width: 3px;\n  }\n  \n  &:hover:before {\n    background: ", ";\n  }\n"], ["\n  cursor: pointer;\n  font-weight: 500;\n  position: relative;\n  user-select: none;\n  transition: color 300ms;\n\n  &:before,\n  &:after {\n    display: inline-block;\n  }\n\n  &:before {\n    background: ", ";\n    border: 1px solid ", ";\n    border-radius: 0;\n    content: \"\";\n    height: 13px;\n    margin: -2px 5px 0 0;\n    transition: background 300ms;\n    vertical-align: middle;\n    width: 13px;\n  }\n\n  &:after {\n    border: solid ", ";\n    border-width: 0 2px 2px 0;\n    content: \"\";\n    height: 7px;\n    left: 5px;\n    position: absolute;\n    opacity: 0;\n    top: 4px;\n    transform: rotate(45deg);\n    transition: border-color 300ms, opacity 300ms;\n    width: 3px;\n  }\n  \n  &:hover:before {\n    background: ", ";\n  }\n"])), Colors.secondary, Colors.grey600, Colors.primary, Colors.grey200);
export var Input = styled.input(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  opacity: 0;\n  position: absolute;\n\n  &:checked + ", ":after {\n    opacity: 1;\n  }\n"], ["\n  opacity: 0;\n  position: absolute;\n\n  &:checked + ", ":after {\n    opacity: 1;\n  }\n"])), Label);
export var Hint = styled.small(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  display: block;\n  color: rgba(0, 0, 0, .5);\n  margin-top: 3px;\n"], ["\n  display: block;\n  color: rgba(0, 0, 0, .5);\n  margin-top: 3px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
//# sourceMappingURL=Checkbox.style.js.map